services:
  cadvisor:
    image: "gcr.io/cadvisor/cadvisor-arm64:v0.49.1"
    container_name: "cadvisor"
    hostname: "cadvisor"
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - 8082:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg

  mysql:
    image: "jc21/mariadb-aria:latest"
    container_name: "mysql"
    hostname: "mysql"
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MARIADB_AUTO_UPGRADE: ${MARIADB_AUTO_UPGRADE}
    volumes:
      - ./data/mysql:/var/lib/mysql

  wetty:
    image: "wettyoss/wetty:latest"
    container_name: "wetty"
    hostname: "wetty"
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - 8083:3000
    command: --ssh-host=${SSH_HOST}

  nginx:
    build:
      context: docker/nginx
      args:
        EMAIL: ${EMAIL}
    container_name: "nginx"
    hostname: "nginx"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:81
    environment:
      TZ: ${TZ}
      DB_MYSQL_HOST: "mysql"
      DB_MYSQL_PORT: ${DB_MYSQL_PORT}
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${DB_MYSQL_NAME}
      DISABLE_IPV6: ${DISABLE_IPV6}
    volumes:
      - ./data/nginx:/data
      - ./data/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - mysql

  fail2ban:
    build:
      context: docker/fail2ban
    container_name: "fail2ban"
    hostname: "fail2ban"
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TZ: ${TZ}
      F2B_LOG_TARGET: "/var/log/fail2ban/fail2ban.log"
      F2B_LOG_LEVEL: ${F2B_LOG_LEVEL}
      F2B_DB_PURGE_AGE: ${F2B_DB_PURGE_AGE}
      SSMTP_HOST: ${SSMTP_HOST}
      SSMTP_PORT: ${SSMTP_PORT}
      SSMTP_HOSTNAME: ${SSMTP_HOSTNAME}
      SSMTP_USER: ${EMAIL}
      SSMTP_PASSWORD: ${SSMTP_PASSWORD}
      SSMTP_TLS: ${SSMTP_TLS}
      SSMTP_STARTTLS: ${SSMTP_STARTTLS}
    volumes:
      - ./data/fail2ban:/var/log/fail2ban
      - ./data/nginx/logs:/var/log/nginx:ro
    depends_on:
      - nginx

  log.io-server:
    build:
      context: docker/log.io-server
    container_name: "log.io-server"
    hostname: "log.io-server"
    restart: unless-stopped
    ports:
      - 8084:6688
    environment:
      TZ: ${TZ}
      LOGIO_SERVER_CONFIG_PATH: "/server.json"
    depends_on:
      - fail2ban

  log.io-file-input:
    build:
      context: docker/log.io-file-input
    container_name: "log.io-file-input"
    hostname: "log.io-file-input"
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      LOGIO_FILE_INPUT_CONFIG_PATH: "/file-input.json"
    volumes:
      - ./data/nginx/logs:/var/log/nginx:ro
      - ./data/fail2ban:/var/log/fail2ban:ro
    depends_on:
      - log.io-server
